In [1]:
import numpy as np

In [2]:
A = np.array([[3, 7], [5, 2]])      

In [3]:
B = np.array([[0, 1, 3], [2, 3, 1], [0, 1, 0]])  

In [4]:
C = np.array([[5, 7, 6, 4, 2], [1, 3, 4, 1, 3], [3, 4, 5, 4, 1]])

## Сингулярное разложение матрицы A

In [5]:
A

array([[3, 7],
       [5, 2]])

In [6]:
U, S, VH = np.linalg.svd(A)

In [7]:
reconstructed_A = U @ np.diag(S) @ VH

In [8]:
reconstructed_A

array([[3., 7.],
       [5., 2.]])

## Сингулярное разложение матрицы B

In [9]:
B

array([[0, 1, 3],
       [2, 3, 1],
       [0, 1, 0]])

In [10]:
U, S, VH = np.linalg.svd(B)

In [11]:
reconstructed_B = U @ np.diag(S) @ VH

In [12]:
reconstructed_B

array([[2.94902991e-16, 1.00000000e+00, 3.00000000e+00],
       [2.00000000e+00, 3.00000000e+00, 1.00000000e+00],
       [0.00000000e+00, 1.00000000e+00, 2.77555756e-17]])

Матрица B была восстановлена с некоторой погрешность. Проверим насколько сильно отличаются значения.

In [13]:
np.testing.assert_allclose(B, reconstructed_B, rtol=0, atol=1e-07)

## Сингулярное разложение матрицы С

In [14]:
C

array([[5, 7, 6, 4, 2],
       [1, 3, 4, 1, 3],
       [3, 4, 5, 4, 1]])

In [15]:
U, S_diagonal, VH = np.linalg.svd(C)

In [16]:
U

array([[-0.75927897,  0.23445293, -0.60706446],
       [-0.3639706 , -0.92629427,  0.09749016],
       [-0.53946348,  0.29497584,  0.78864974]])

In [17]:
S = np.zeros((3, 5), dtype=np.float64)

In [18]:
np.fill_diagonal(S, S_diagonal)

In [19]:
S

array([[14.94713352,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  2.72739944,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.46440832,  0.        ,  0.        ]])

In [20]:
VH

array([[-0.38661298, -0.57300074, -0.58264507, -0.37190679, -0.21073828],
       [ 0.41464331,  0.01546935, -0.3019654 ,  0.43683401, -0.73879941],
       [-0.39052151, -0.5479222 ,  0.47174175,  0.56256936, -0.09082761],
       [-0.43720626,  0.36725326, -0.53062765,  0.5481159 ,  0.30328039],
       [ 0.5787443 , -0.48614521, -0.2554127 ,  0.23226293,  0.55635974]])

In [21]:
reconstructed_C = U @ S @ VH

In [22]:
reconstructed_C

array([[5., 7., 6., 4., 2.],
       [1., 3., 4., 1., 3.],
       [3., 4., 5., 4., 1.]])